In [1]:
import numpy as np

zadanie 1

In [2]:
a_small_one = np.arange(1,65).reshape((8,8))
a_small_one

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

zadanie 2

In [3]:
print('suma w kolumnach')
print(a_small_one.sum(axis=0))
print('suma w wierszach')
print(a_small_one.sum(axis=1))
print('średnia')
print(a_small_one.sum(axis=1)/8)

suma w kolumnach
[232 240 248 256 264 272 280 288]
suma w wierszach
[ 36 100 164 228 292 356 420 484]
średnia
[ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5]


zadanie 3

In [4]:
print(a_small_one[a_small_one % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]


zadanie 4

In [5]:
no_even_small_one = a_small_one.astype(float)
no_even_small_one[no_even_small_one % 2 == 0] = np.nan
no_even_small_one

array([[ 1., nan,  3., nan,  5., nan,  7., nan],
       [ 9., nan, 11., nan, 13., nan, 15., nan],
       [17., nan, 19., nan, 21., nan, 23., nan],
       [25., nan, 27., nan, 29., nan, 31., nan],
       [33., nan, 35., nan, 37., nan, 39., nan],
       [41., nan, 43., nan, 45., nan, 47., nan],
       [49., nan, 51., nan, 53., nan, 55., nan],
       [57., nan, 59., nan, 61., nan, 63., nan]])

zadanie 5


In [6]:
print("Suma dla każdego wiersza ")
print(np.nansum(no_even_small_one, axis=1))

print("Średnia dla każdej kolumny")
print(np.nanmean(no_even_small_one, axis=0))

print('wartość najmniejszą i w całej tablicy')
print(np.nanmin(no_even_small_one))

Suma dla każdego wiersza 
[ 16.  48.  80. 112. 144. 176. 208. 240.]
Średnia dla każdej kolumny
[29. nan 31. nan 33. nan 35. nan]
wartość najmniejszą i w całej tablicy
1.0


<ipython-input-6-2f559f7f74c3>:5: RuntimeWarning: Mean of empty slice
  print(np.nanmean(no_even_small_one, axis=0))


In [7]:
no_even_small_one

array([[ 1., nan,  3., nan,  5., nan,  7., nan],
       [ 9., nan, 11., nan, 13., nan, 15., nan],
       [17., nan, 19., nan, 21., nan, 23., nan],
       [25., nan, 27., nan, 29., nan, 31., nan],
       [33., nan, 35., nan, 37., nan, 39., nan],
       [41., nan, 43., nan, 45., nan, 47., nan],
       [49., nan, 51., nan, 53., nan, 55., nan],
       [57., nan, 59., nan, 61., nan, 63., nan]])

zadanie 6

In [8]:
watosci_1 = np.where(np.isnan(no_even_small_one), 1, no_even_small_one)
no_even_small_one = np.where(np.isnan(no_even_small_one), a_small_one, no_even_small_one)
print("Tablica po wstawieniu wartości za nan:\n", watosci_1 )
print("Tablica po przywróceniu parzystych wartości:\n", no_even_small_one)

Tablica po wstawieniu wartości za nan:
 [[ 1.  1.  3.  1.  5.  1.  7.  1.]
 [ 9.  1. 11.  1. 13.  1. 15.  1.]
 [17.  1. 19.  1. 21.  1. 23.  1.]
 [25.  1. 27.  1. 29.  1. 31.  1.]
 [33.  1. 35.  1. 37.  1. 39.  1.]
 [41.  1. 43.  1. 45.  1. 47.  1.]
 [49.  1. 51.  1. 53.  1. 55.  1.]
 [57.  1. 59.  1. 61.  1. 63.  1.]]
Tablica po przywróceniu parzystych wartości:
 [[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]]


zadanie 7

In [9]:
sto_by_sto = np.random.rand(100,100)
sto_by_sto

array([[0.61888716, 0.32381543, 0.71358295, ..., 0.7375096 , 0.53259457,
        0.8149309 ],
       [0.6472504 , 0.93222124, 0.98717612, ..., 0.08630702, 0.05628555,
        0.58316999],
       [0.39088599, 0.52081569, 0.13131902, ..., 0.94134945, 0.62364349,
        0.30017973],
       ...,
       [0.84777807, 0.89201408, 0.89885336, ..., 0.1252396 , 0.7453553 ,
        0.45939511],
       [0.78206497, 0.88851854, 0.41434609, ..., 0.61354793, 0.80664723,
        0.03799145],
       [0.61484304, 0.97806548, 0.6316776 , ..., 0.32038788, 0.66789165,
        0.54860617]])

zadanie 8

In [21]:
mean_rows = np.mean(sto_by_sto, axis=1)
mean_cols = np.mean(sto_by_sto, axis=0)

mean_abs_diff_rows = np.mean(np.abs(mean_rows - 0))
mean_abs_diff_cols = np.mean(np.abs(mean_cols - 0))

thousand_by_thousand = np.random.randn(1000, 1000)


def calculate_mean_rows(arr):
  return np.mean(arr, axis=1)


def calculate_mean_cols(arr):
  return np.mean(arr, axis=0)

time_mean_rows = timeit.timeit(lambda: calculate_mean_rows(thousand_by_thousand), number=100)
time_mean_cols = timeit.timeit(lambda: calculate_mean_cols(thousand_by_thousand), number=100)

print(time_mean_rows)
print(time_mean_cols)




0.04394108599998958
0.055099208000001454


zadanie 9

In [31]:
import numpy as np
import timeit
import pickle
from numpy import savez_compressed
from numpy import load

thousand_by_thousand = np.arange(1, 10001).reshape((100, 100))
thousand_by_thousand


# Zapis do pliku tekstowego
def save_to_txt(arr, filename):
  np.savetxt(filename, arr)

def load_from_txt(filename):
  return np.loadtxt(filename)

# Zapis do pliku pickle
def save_to_pickle(arr, filename):
  with open(filename, 'wb') as f:
    pickle.dump(arr, f)

def load_from_pickle(filename):
  with open(filename, 'rb') as f:
    return pickle.load(f)


# Zapis do pliku skompresowanego
def save_to_compressed(arr, filename):
  savez_compressed(filename, arr)

def load_from_compressed(filename):
  loaded = load(filename + '.npz')
  return loaded['arr_0']


filename_txt = 'array_txt.txt'
filename_pickle = 'array_pickle.pkl'
filename_compressed = 'array_compressed'


time_save_txt = timeit.timeit(lambda: save_to_txt(thousand_by_thousand, filename_txt), number=1)
time_load_txt = timeit.timeit(lambda: load_from_txt(filename_txt), number=1)

time_save_pickle = timeit.timeit(lambda: save_to_pickle(thousand_by_thousand, filename_pickle), number=1)
time_load_pickle = timeit.timeit(lambda: load_from_pickle(filename_pickle), number=1)

time_save_compressed = timeit.timeit(lambda: save_to_compressed(thousand_by_thousand, filename_compressed), number=1)
time_load_compressed = timeit.timeit(lambda: load_from_compressed(filename_compressed), number=1)

print(f"Czas zapisu do pliku tekstowego: {time_save_txt}")
print(f"Czas odczytu z pliku tekstowego: {time_load_txt}")
print(f"Czas zapisu do pliku pickle: {time_save_pickle}")
print(f"Czas odczytu z pliku pickle: {time_load_pickle}")
print(f"Czas zapisu do pliku skompresowanego: {time_save_compressed}")
print(f"Czas odczytu z pliku skompresowanego: {time_load_compressed}")


Czas zapisu do pliku tekstowego: 0.013901106000048458
Czas odczytu z pliku tekstowego: 0.0024847320000844775
Czas zapisu do pliku pickle: 0.001830395999945722
Czas odczytu z pliku pickle: 0.00016023199998471682
Czas zapisu do pliku skompresowanego: 0.00892970199993215
Czas odczytu z pliku skompresowanego: 0.0011178679999375163


In [32]:
thousand_by_thousand = np.arange(1, 10001).reshape((100, 100))
thousand_by_thousand

array([[    1,     2,     3, ...,    98,    99,   100],
       [  101,   102,   103, ...,   198,   199,   200],
       [  201,   202,   203, ...,   298,   299,   300],
       ...,
       [ 9701,  9702,  9703, ...,  9798,  9799,  9800],
       [ 9801,  9802,  9803, ...,  9898,  9899,  9900],
       [ 9901,  9902,  9903, ...,  9998,  9999, 10000]])